services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\Bluesky\:
    resource: '../Classes/*'

  In2code\Bluesky\Domain\Repository\BlueskyRepository:
    public: true
